[package]
name = "hyperlane-dusk-types"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
bytecheck = { workspace = true }
dusk-core = { workspace = true, optional = true }
dusk-bytes = { version = "0.1.7", optional = true }
dusk-forge = { workspace = true, optional = true }
rkyv = { workspace = true }
serde = { workspace = true, optional = true }

[features]
serde = ["dep:serde", "dep:dusk-bytes"]
drc20 = ["dep:dusk-core"]
abi = ["drc20", "dep:dusk-bytes", "dep:dusk-forge", "dusk-core/abi-dlmalloc"]

[dev-dependencies]
canonical-dusk-contract-standards = { package = "dusk-contract-standards", git = "https://github.com/dusk-network/contracts", rev = "bc1b00ee0af059975e158b7b580b4d0c0f1bdf9f" }
canonical-dusk-core = { package = "dusk-core", version = "=1.6.0" }

[[test]]
name = "drc20_abi"
required-features = ["drc20"]
