[package]
name = "hyperlane-dusk-data-driver"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dusk-data-driver = { workspace = true }
hyperlane-dusk-types = { workspace = true, features = ["serde", "drc20"] }

[features]
ffi = ["dusk-data-driver/wasm-export"]
js = ["ffi", "dusk-data-driver/alloc"]
